export const CustomExceptions = {
  auth: {
    AlreadyRegistered: 'User with this email already exists',
    NotTheSamePasswords: 'Not the same passwords',
    InvalidCred: 'Invalid credentials',
    InvalidRefresh: 'Invalid refresh token',
  },
  businessAccount: {
    AlreadyHave: 'You already have a business account',
  },
  locations: {},
  user: {
    NotFound: 'User not found',
  },
};
